// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/menu': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/menu.get').default>>>>
    }
    '/api/toppings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/toppings.get').default>>>>
    }
    '/api/transactions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/transactions/[id].delete').default>>>>
    }
    '/api/transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/transactions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/transactions/index.post').default>>>>
    }
    '/api/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../middleware/cors').default>>>>
    }
  }
}
export {}